[mirror]
directory = /12-tb/pypimirror-fixed
json = false
master = https://pypi.org
timeout = 10
workers = 10
hash-index = false
storage-backend = filesystem
verifiers = 3
keep_index_versions = 0
release-files = true
compare-mirrors = false

[plugins]
enabled =
    regex_release_file_metadata
    latest_release

[regex_release_file_metadata]
any:release_file.filename =
    .*-cp310-.*-manylinux.*x86_64.*\.whl$
    .*-cp310-.*-linux_x86_64\.whl$
    .*-abi3-manylinux.*x86_64.*\.whl$
    .*-abi3-linux_x86_64\.whl$
    .*-none-any\.whl$

[latest_release]
keep = 3
